name: deploy_to_lambda

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      # Set Lambda Function Name Here, space separated
      LAMBDA_LAYER_NAMES: "KIH_API"
      # Set Lambda Function Name Here

      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-southeast-1
      AWS_DEFAULT_OUTPUT: table

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      # Set up required applications
      - run: sudo apt-get install zip
      - run: sudo apt-get install awscli

      #       Package and deploy layer
      - run: mkdir python
      - run: pip install -r requirements.txt -t python
      - run: cp -R * new_subdir
      - run: zip -r layer.zip python
      - run: for layer in $LAMBDA_LAYER_NAMES; do aws lambda publish-layer-version --layer-name $layer-layer --zip-file fileb://layer.zip --compatible-runtimes python3.9; done
